---
title: "ECNS Final Report"
author: "Landon Sielaff"
date: "`r Sys.Date()`"
output: html_document
---

# Final Exploratory Analysis

### Introduction

Over the past 18 years, almost 2 million people have purchased elk tags to hunt in Montana, generating over $250 million dollars. Hunting in Montana is every outdoorsmans dream and it plays a key role in managing conservation in the state and providing an alternative way for economic development. For this project I wanted to look at Montana Fish, Wildlife and Parks public data to determine which hunting districts are the best for elk hunting. This project is important to me because I have always been an avid outdoorsman and since moving to Montana, it has been hard for me to put in the time and effort to scout every possible hunting unit to find the best places to hunt. 

To start this project, I first conducted a descriptive analysis on the two different types of residency (resident and non-resident) to quickly calculate the average harvest rates of elk, bull elk and bull elk with six or more points(mature bulls) over the 17 years of data. To do this, I took the amount of harvested bulls divided by the total number of hunters. The results of this analysis showed that non-resident hunters have the highest harvest rate in all three statistics, having an average elk harvest rate of 28.65%, an average bull harvest rate of 19.28% and an average mature bull harvest rate of 9.04%. Coming in at much lower rates, Montana residents had an average elk harvest rate of 22.26%, an average bull harvest rate of 9.72% and an average mature bull harvest rate of only 4.07%.To put this into a more understandable statistic, almost one in three non-resident hunters are successful in harvesting an elk every year while only one in 5 residents are successful. After running a descriptive analysis I wanted to see how these rates have changed over time. I created a time series to see how the amount of hunters have grown over the last 17 years as well as to see how the harvest rates have changed. After creating the graphs, the most obvious data point was that the number of non-resident hunters in Montana has been on an upward trend year over year, while the number of resident hunters was quite stationary. 

Another interesting observation was that the average harvest rate for non-resident hunters was substantially more that the average harvest rate for residents. I created another line graph to show how the harvest rates for each year has changed for both non-residents and residents and the results showed that again the residents had a substantially more stationary trend compared to the slightly increasing trend from the non-residents harvest rates. An additional analysis I conducted was the average days per hunter for both non-resident and resident. The results showed that on average, non-residents spend more days hunting that residents. This makes sense logically because if a non-resident is spending upwards of $1,500, it would make sense that they spend more days hunting because they are trying to make the purchase worth it. This would also explain why on average non-residents had a higher harvest rate than residents.


### Methods

After completing a descriptive analysis, I then want to merge the harvest reports with hunting district spatial data to find which hunting unit with the highest rate of harvest. In Montana and many other states hunting units are treated the same as counties in the sense that it is a vehicle that the government uses to better regulate regions to have better and more accurate testings and implementations of new policies. The units of analysis I looked at were the number of elk harvests per hunting unit. In order to analyze this data, I needed to first process the data into a clean format. I first did this by loading both the Montana Fish, Wildlife and Parks Harvest report data from 2004 - 2021 into the RScript. This data was formatted in a list and separated by Resident, Nonresident and Sum. This made it difficult to analyze, so I created a data frame for each year and each residency type. This resulted in 54 data frames with its own unique data from each of the 15 attributes (License Year, Hunting Districts, Residency, Hunters, Days, Days Per Hunter, Total Harvest, Bulls, Cows, Calves, Bow, Rifle, Spike Bull Elk, Less Than 6 Points, 6 Points or More). Given this project's time constraints, I choose to look at the total harvests from both residents and non-residents. After creating the unique data frames, I needed to create a data frame that contained the spatial data from each of the hunting districts, so I imported the Deer and Elk Hunting Districts from the Montana Wildlife, Fish and Parks database. This data frame contains geometric data that allows me to visually plot the data the same way we looked at the California data in the Spatial Analysis Lecture. In order to visually show the harvest districts with the most harvests of each of the three categories (Total Harvests, Bulls, Bulls with 6 or More Points), I needed to merge the harvest data with the geometric data from the hunting districts.

The first problem I ran into was that there was verifying hunting districts from each of the 18 years of data. This is due to the fact that hunting districts change in response to the herd management and regulations put in place by MFWP. To get around this problem, I needed to find which index from each of the different years harvest data that references the current hunting units for the 2021 season. I did this by creating a master index data frame that tracked the different indexes in each data frame that related to the hunting districts that I wanted to analyze. To merge the data sets, I created a new data frame for each of the attributes that I wanted to analyze, which were created from the original spatial data frame from the hunting districts. I then used the master index data frame to reference the correct columns from each of the 18 years and added those columns to the corresponding hunting districts.

In conducting this analysis, I did not find a need to conduct any transformations. Since the data that I am analyzing is purely descriptive, it was best to keep the data as is. While I did not conduct any transformations, the data did contain missing values due to regions in Montana that do not allow hunting. These regions included Indian Reservations, National Parks and Lakes. This data shows as white on the plots. After submitting my draft exploratory analysis, I decided to find the cumulative harvest data from all of the 17 years and display this data for each of the six analyses, non-resident total elk harvests (2004-2021), non-resident total bull elk harvests (2004-2021), non-resident total mature bull elk harvests (2004-2021), resident total elk harvests (2004-2021), resident total bull elk harvests (2004-2021) and resident total mature bull elk harvests (2004-2021) . The top 3 most popular units for non-residents was District 121, District 360 and District 313 while the top three most popular units for residents were District 380, District 270 and District 121. This is over the last 17 years, I know when looking at more recent years the most popular units have changed. 


### Montana Elk Harvest Analysis

To complete the elk harvest analysis, I compared the last 17 years of harvest data to determine which units presented the best opportunities for hunting. The findings from the total harvest analysis showed that the top three units that outputted the most harvested elk for non-residents were District 360 with 2,729 elk harvested, District 313 with 2,275 elk harvested, and District 314 with 2,225 elk harvested. The top three units that outputted the most harvested elk for Montana residents were District 380 with 10,554 elk harvested, District 410 with 9,261 elk harvested, and District 393 with 8,202 elk harvested. 

The hunting district that stood out for hosting the largest number of elk harvests for non-residents was District 360, which is the North Madison District, located southeast of Ennis, Montana. The North Madison District contains over 650 square miles of land, 55% which is public land and almost 40% that is considered forest and woodland. Due to these statistics, it makes sense why it is the most popular hunting unit for non-resident hunters. The hunting district that stood out for hosting the largest number of elk harvests for residents was District 380, which is the Radersburg District, located southeast of Helena, Montana. The Radersburg District contains over 1,000 square miles of land, with over 50% being public. 


### Montana Bull Elk Harvest Analysis

After completing the analysis on total elk harvests, the next thing I looked at was the units with the highest total bull elk harvests. I conducted the same analysis as I did for total harvest, but just looked at the data from bulls. The findings from the total elk harvest analysis showed that the top three units that outputted the most harvested bull elk for non-residents were District 313 with 2,149 bull elk harvested, District 360 with 1,800 bull elk harvested, and District 314 with 1,603 bull elk harvested. The top three units that outputted the most harvested bull elk for Montana residents was again District 380 with 4,944 bull elk harvested, District 215 with 3,786 bull elk harvested, and District 270 with 3,734 bull elk harvested. 

After analyzing the districts with the highest total bull elk harvests, District 380 once again stands out as a prosperous unit for elk hunting, when targeting bulls as a resident. For non-residents on the other hand, District 313 stood out as the best unit. District 313 is the Gardiner District and is located just north of the northern entrance to Yellowstone National Park. The Gardier district is well known for the abundance of public land with over 80% being public. 


### Montana Mature Bull Elk Harvest Analysis

To further analyze each of the units, I looked at the units with the best harvest rates for mature bulls with 6 or more points. This analysis is important because while many hunters use hunting as a tool to put meat on the table and provide for their family in an alternative way, but many non-resident hunters are more driven by the size of the elk they bring home. This is formally known as “trophy hunting” and it is a very controversial topic in the hunting community. Many people are under-educated when it comes to trophy hunting though. In the case of elk hunting, a mature bull elk is usually between 6 and 10 years old and nearing the end of its lifetime. Most elk that make it to this age have battle scars and become weak, making them an easy target for predators and disease. Harvesting mature animals is a healthy part of conservation because it allows for the younger bulls to become eligible for breeding, ultimately generating a more healthier herd. 

The findings from the bull harvest with 6 or more points analysis show that the top three units that outputted the most harvested mature bull elk for non-residents were District 313 with 1,163 mature bull elk harvested, District 314 with 941 mature bull elk harvested, and District 393 with 920 mature bull elk harvested. The top three units that outputted the most harvested mature bull elk for Montana residents were District 410 with 2,375 bull elk harvested, District 700 with 2,037 bull elk harvested, and District 393 with 1,370 bull elk harvested. 

This analysis is the most interesting in my opinion because it really goes to show how difficult it is to harvest a mature bull elk. For non-residents, the unit that produces the most harvested mature bull elk is once again District 313, the Gardiner District. For residence, this is where it gets interesting. Neither District 410 or District 700 have been in the previous top three units for elk and bull elk harvests. Districts 410 and 700 are formally known as the Missouri Breaks Districts. These two districts are neighboring districts located in central Montana. These two districts have a combined square mileage of over 4,200 with over 350 square miles of water and 1,771 square miles of public land. These districts have been well known for producing healthy, mature bulls for a while and continue to keep up to all of its expectations.


### Montana Elk Harvest Rate Analysis

After analyzing the number of elk harvested, I wanted to look at the rates at which elk are harvested in each of the different hunting units to see which units provided the highest likelihood for a harvest. In order to calculate harvest rate, I took the total harvested number divided by the total amount of hunters for each unit. The results of the analysis showed that for non-residents, the units that produced the highest likelihood for harvesting elk was District 390 for both elk and bull elk harvest with harvest rates of 63.72% and 48.92% respectively. District 390 is the Sixteenmile Creek District located north of the Bridger Mountain range. The district that had the highest harvest rate for mature bulls was District 455, the Beartooth Wildlife Management Area District located northeast of Helena, Montana with a harvest rate of 32.88%. For residents, the district with the highest likelihood of harvest for all three analysis was anonymously District 455, the Beartooth Wildlife Management Area District with harvest rates for elk being 58.02%, harvest rates for bull elk being 25.76% and harvest rates for mature bull elk being 17.5%. 


### Conclusion

After conducting the analysis on harvest reports in the state of Montana, it is clear that for non-residents, the Gardiner District 313 is the best district for all around quality elk hunting, while the Sixteenmile Creek District 390 proved to have outstanding harvest rates. The recommendation for residents on the other hand is hands down the Missouri Breaks Districts410 and 700 due to the abundance of public land and amazing mature bull harvest numbers. Other notable units to mention are the Beartooth Wildlife Management Area District 455 due to the large harvest rates. Overall, Montana is a stand out state when it comes to elk hunting, blowing the national elk success rate of 15% out of the water. Montana’s diverse geography brings in hunters from all 49 other states while providing enough room for residents to continue to go out and have successful hunts. Additional analysis that I would like to conduct would be to include drawing statistics for each unit to see how they play into the harvest rates. An additional analysis that I want to complete is to add in weather, elevation and land ownership type (public vs private) to see how these variables affect and/or are correlated with the harvest statistics. This project was great for me to really get to understand Montana elk hunting on a deeper level and make more educated decisions for where I am planning to hunt next season.
